fix: support http component layer config
serverless-tencent/yaml-parser pull request #1
Opened 2021-07-26 12:37 UTC by LinLzis

2021-07-26 12:41 UTC, yugasun requested changes

2021-07-26 12:41 UTC, yugasun commented on src/parse.ts
> +      isHttpFramework(slsOptions.component, slsOptions.inputs.faas.framework)
这里直接判断 yaml 中 `component` 字段是否为 `http` 是不是更好一点？

2021-07-26 12:45 UTC, LinLzis commented on src/parse.ts
> +      isHttpFramework(slsOptions.component, slsOptions.inputs.faas.framework)
OK

2021-07-27 02:20 UTC, yugasun approved these changes

2021-07-27 02:31 UTC, merged

2021-07-27 02:33 UTC, slsplus commented
:tada: This PR is included in version 0.1.2 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@slsplus/yaml-parser/v/0.1.2)
- [GitHub release](https://github.com/serverless-tencent/yaml-parser/releases/tag/v0.1.2)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: